### PR TITLE
Fix JavaDoc compilation issues

### PR DESCRIPTION
**Pull request by xstefank**
Signed-off-by: xstefank <xstefank122@gmail.com>

### CODE REVIEW

**Comment by xstefank** [comment]
@rdebusscher this is failing snapshot builds (the last one is Sept 27th). I will merge this now but we can adjust it in every case if you find something you would disagree with later.

**Comment by xstefank** [comment]
@mmusgrov do you mind if we merge this now?

**Comment by rdebusscher** [comment]
@xstefank If I remember correctly, locally everything was fine. Anyway, no problem in merging this.

**Comment by xstefank** [comment]
@rdebusscher no worries. These things happen. Maybe we can convince Eclipse to run CI for PRs not only snapshots.

**Comment by xstefank** [comment]
Merging myself as this is all green and it's failing nighly builds.

**Pull request merged**
