### PR TITLE
Move to the MicroProfile parent

### PR DESCRIPTION
**Pull request by xstefank**
The first step in #351. This is a bigger change that is not directly tight to Jakarta alignment but it is a prerequisite.

### CODE REVIEW

**Comment by mmusgrov** [comment]
I will schedule a review of this this week unless anyone else cares to look at it before then,

**Review by mmusgrov — APPROVED** [review]
Our apologies for taking so long to review this one.
The changes seem to be good.
I tried to compare the diffs with the example (microprofile-config) and this PR is doing something similar.
I assume you you reformatted the javadoc in order to meet some style check introduced by the parent, in which case fine.
Likewise for the code reformatting.
And similarly for the pom changes (ie in order to work with the parent).

Once again, we appreciate you doing this big task, thanks.

**Comment by mmusgrov** [comment]
@xstefank this PR seems uncontentious so I'd say it is fine to merge with just one reviewer.

**Comment by xstefank** [comment]
@mmusgrov agreed. I'll merge this so I can proceed with the jakarta changes. Thanks for the review.

-- the formating is now done automatically on compile.

**Pull request merged**
