### PR TITLE
Add missing leaveUrl parameter to LRAClient#updateCompensator

### PR DESCRIPTION
**Pull request by xstefank**
Signed-off-by: xstefank <xstefank122@gmail.com>

### CODE REVIEW

**Comment by mmusgrov** [comment]
@xstefank My point was that there are two join methods so you need to have two updateCompensator methods as well.

**Comment by xstefank** [comment]
@mmusgrov should I then update this PR to add that method?

**Comment by xstefank** [comment]
I will add it to this PR. If the outcome of the discussion will be to remove URLs methods I will update this PR to just add a new updateCompensator method

**Comment by xstefank** [comment]
superseded by https://github.com/eclipse/microprofile-lra/pull/55

**Pull request closed without merging**
