### PR TITLE
Using LRAClient get status in tck instead of management spi status

### PR DESCRIPTION
**Pull request by ochaloup**

### CODE REVIEW

**Comment by mmusgrov** [comment]
+1

**Comment by xstefank** [comment]
I quite like these convenience methods  like`isActive()`, `isComplete()`. Will we be adding them to the LRAStatus?

**Comment by ochaloup** [comment]
@mmusgrov nice. I do not have rights for merging this. I'm not sure if you can merge this or should this be acknowledged and merged by @rdebusscher? (sorry for my ignorance)

@xstefank seems reasonable. I can try to create new PR. Would that be fine?

**Comment by xstefank** [comment]
@mmusgrov @ochaloup definitely not in this one, we can do that anytime :)

**Comment by ochaloup** [comment]
@mmusgrov ...then this PR could be merged, right?

**Comment by mmusgrov** [comment]
The procedure is

> so long as we have a Approve review from a committer from a different company to the company initiating the pull request it should be OK for a committer from the original company to merge it

ie we need @rdebusscher to provide a review before I can merge it.

**Comment by ochaloup** [comment]
@mmusgrov thank you for clarification and reminding me the process
@rdebusscher thanks :)

**Comment by mmusgrov** [comment]
@ochaloup I cannot find a matching issue for this. In the future when raising a PR can we always include a link to the associated issue.

**Pull request merged**
