### PR TITLE
Non-JAX-RS complete/Compensate: allow String parameters

### LINKED ISSUE #160: Allow String parameters as parameter type for Complete and Compensate Methods in the non JAX-RS case
Through Issue https://github.com/eclipse/microprofile-lra/issues/35 (PR https://github.com/eclipse/microprofile-lra/pull/148) the only allowed parameter type on the Complete and Compensate Methods is `java/net.URI`

    @Compensate
    public void compensateAction(URI lraId) {

However, in the JAX-RS version, the most common parameter types will be String.

    @PUT
    @Path("/compensate")
    @Produces(MediaType.APPLICATION_JSON)
    @Compensate
    public Response compensateWork(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) String lraId) {

In order to make the spec more uniform, String should also be allowed as parameter types for Complete and Compensate Methods in the non JAX-RS case.

    @Compensate
    public void compensateAction(String lraId) {

### PR DESCRIPTION
**Pull request by rdebusscher**
Fixes #160.

### CODE REVIEW

**Comment by rdebusscher** [comment]
@xstefank Your feedback is also appreciated.

**Comment by rdebusscher** [comment]
@mmusgrov the LRA id **MUST** be an URI, since for the Complete and Compensate methods in the non-jaxrs case, we require URI as parameter type.

**Comment by mmusgrov** [comment]
@rdebusscher That's a shame

**Comment by rdebusscher** [comment]
@mmusgrov We can remove any reference to URI in the API and Spec and replace it with String and define in the spec that LRA id must be a unique String and preferably a URI.

**Comment by xstefank** [comment]
@rdebusscher sorry, I don't agree with this. URI (previously URL) enforces uniqueness. URI can always be transformed to String (in header or in non-JAX-RS with this PR) but not other way around. I think the spec is more robust if the uniqueness is mandated by the API. My 2c.

**Comment by rdebusscher** [comment]
We are going for URI type only. See #163 for the required changes.

**Pull request closed without merging**
